### ISSUE TITLE
A bug

### ISSUE THREAD

**Issue by IFIF1727** [zhousinan/WordBookPlusAbout#2] opened 2023-09-15 14:57 UTC
the words' pronunciations are wrong.
if I click the first word's  pronunciations, the second word's pronunciation would be same as the first one.
I very like your software. Would you mind fixing it?

**Comment by zhousinan** [comment] 2023-09-15 16:32
I am appreciated for your report. Could you please tell me more information about the issue? (What page, what funtion)

**Comment by IFIF1727** [comment] 2023-09-16 01:48
I made a screen recording vidoe, and you can open the below url
[https://drive.google.com/file/d/16KzqLevDFsVHsqq5DJhVdNGOzTJhAWgQ/view?usp=sharing](url)

**Comment by IFIF1727** [comment] 2023-09-16 01:55
you will see the pronunciations are always the first and the second words's, when I click other words

**Comment by zhousinan** [comment] 2023-09-16 04:26
Thank you for your feedback! 😊 The issue is now fixed in my code. But the app might not be updated in the store soon, because there are some works needed to be done before update. I hope you could wait before the revised version releases.

**Comment by zhousinan** [comment] 2023-10-07 05:21
The update is now available in Microsoft Store!

**Closed by zhousinan** 2023-10-07 05:21 UTC
